In [1]:
import numpy as np

In [2]:
np.ones(10, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [3]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9


In [5]:
arr.ndim

1

In [6]:
a = np.array([[1, 2, 3],[ 4, 5, 6],[ 7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a.ndim

2

In [8]:
arr.shape

(9,)

In [9]:
a.shape

(3, 3)

In [10]:
arr.size

9

In [11]:
a.size

9

In [12]:
len(a)

3

In [13]:
len(arr)

9

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a[0,1]

2

In [17]:
ai=[1,2]


In [18]:
a[ai]

array([[4, 5, 6],
       [7, 8, 9]])

In [19]:
list=[1,2,3,4]
list

[1, 2, 3, 4]

In [20]:
for i in list:
    print(i*i)

1
4
9
16


In [21]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [22]:
%timeit [i**2 for i in list]

424 ns ± 3.45 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
%timeit [arr*arr]

619 ns ± 8.46 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [24]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ar=np.array([1,2,3,4])
ar

array([1, 2, 3, 4])

In [26]:
%timeit [ar*ar]

623 ns ± 7.87 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [27]:
arr**arr

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489])

In [28]:
ls=['j','p','l',3.5,3,True]

In [29]:
[print(i) for i in ls]

j
p
l
3.5
3
True


[None, None, None, None, None, None]

In [30]:
ar2=np.array([True, False,'.1'])

In [31]:
ar2

array(['True', 'False', '.1'], dtype='<U5')

In [32]:
type(ar2)

numpy.ndarray

In [33]:
## BOOLEAN < INTEGER < FLOAT <STRING

In [34]:
first_2d_array = np.array([[1,2,3],[2,4,6],[9,5,3],[1,5,9]])

In [35]:
first_2d_array.shape

(4, 3)

In [36]:
len(first_2d_array)

4

In [37]:
first_2d_array.size

12

In [38]:
first_2d_array

array([[1, 2, 3],
       [2, 4, 6],
       [9, 5, 3],
       [1, 5, 9]])

In [39]:
first_2d_array.ndim

2

In [40]:
arr2= np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr2**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [42]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
np.arange(10,110,11)

array([ 10,  21,  32,  43,  54,  65,  76,  87,  98, 109])

In [44]:
arr2[5:9]

array([6, 7, 8, 9])

In [45]:
arr2[2],arr2[3],arr2[5]

(3, 4, 6)

In [46]:
indexes =[2,7,8]

In [47]:
arr2[indexes]

array([3, 8, 9])

In [48]:
arr3= np.array([[1,2],[4,5]])

In [49]:
arr3

array([[1, 2],
       [4, 5]])

In [50]:
arr3.shape

(2, 2)

In [51]:
arr3.size

4

In [52]:
len(arr3)

2

In [53]:
arr3[0,1]

2

In [54]:
arr3[[0,1],[1,0]]

array([2, 4])

In [55]:
a= np.arange(11)

In [56]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr3[0]

array([1, 2])

In [58]:
arr3[1]

array([4, 5])

In [59]:
i=5
q=i%2==0
q

False

In [60]:
mask = a%2 ==0
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [61]:
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [62]:
a[mask]

array([ 0,  2,  4,  6,  8, 10])

In [63]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [64]:
## fetch element which are divisble by euither 2 or 3

In [65]:
mask2 = a%2==0

In [66]:
mask3 = a%3==0

In [67]:
masked = mask2 | mask3

In [68]:
a[masked]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [69]:
mask2 | mask3

array([ True, False,  True,  True,  True, False,  True, False,  True,
        True,  True])

In [70]:
a[masked]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [71]:
cool_array =np.arange(1,101)

In [72]:
cool_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [73]:
mask = cool_array%2==0
cool_array[mask]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [74]:
np.where(cool_array%2==0,'even','odd')

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even'], dtype='<U4')

In [75]:
## sensor that measure height (~65 height)
## sensor if faulty : -1
## remove all corrupted entries 
height= np.array ([62.3 , 66. , 62.7 , -1 , 67.5 , 63.3 , 67.7 , 64.1 ,-1. ,63.7])

In [76]:
height

array([62.3, 66. , 62.7, -1. , 67.5, 63.3, 67.7, 64.1, -1. , 63.7])

In [77]:
mask = np.where(height==-1 , 'False', 'True') ## true and false whoud not be in inverted comma

In [78]:
mask

array(['True', 'True', 'True', 'False', 'True', 'True', 'True', 'True',
       'False', 'True'], dtype='<U5')

In [79]:
height[mask]

IndexError: arrays used as indices must be of integer (or boolean) type

In [ ]:
mask

In [ ]:
height= np.array ([62.3 , 66. , 62.7 , -1 , 67.5 , 63.3 , 67.7 , 64.1 ,-1. ,63.7])

In [ ]:
height

In [ ]:
m=np.where(height>0,True,False)

In [ ]:
height[m]

In [ ]:
##NPS - aribnb

In [ ]:
score = np.loadtxt('survey.txt')

In [ ]:
score

In [ ]:
type(score[1])

In [ ]:
score = np.loadtxt('survey.txt', dtype=int)

In [ ]:
score

In [ ]:
type(score[1])

In [ ]:
score.size

In [ ]:
len(score)

In [ ]:
score.ndim

In [ ]:
score.max()

In [ ]:
score.min()

In [ ]:
## NPS = % Promoters - % detractors
# 1-6 detractors
# 7,8 passives
# 9,10 promoters

In [ ]:
promoter= np.where(score > 8,True, False)
promoter

In [ ]:
promoter_count = score[promoter].size
promoter_count

In [ ]:
detractor= np.where(score < 7,True, False)
detractor

In [ ]:
detractor_count= score[detractor].size
detractor_count

In [ ]:
NPS = round(((promoter_count/score.size)-(detractor_count/score.size))*100,2)
NPS

In [ ]:

                                            ## NUMPY 3 IMAGE MANIPULATION

In [ ]:
# empty array

In [ ]:
e= np.empty(5, dtype='U10') ## unicode stirng for max character = 10

In [ ]:
e

In [ ]:
e[0]='aghaogrhaoighrpieg' 
e

In [ ]:
e=np.empty(5,dtype='str') ## unicode stirng for max character 

In [ ]:
e

In [ ]:
e[0]='scaler'

In [ ]:
e

In [ ]:
a= np.arange(1,5)

In [ ]:
a

In [ ]:
b=a[::-1]
b

In [ ]:
a<b ## element wise comparission

In [ ]:
# is any value in a less than b ?? T or F

In [ ]:
## ANY FUNCTION

In [ ]:
np.any(a<b)

In [ ]:
a>b

In [ ]:
np.any(a>b)

In [ ]:
a

In [ ]:
b=a*10
b

In [ ]:
np.any(a>b)

In [ ]:
a=np.array([1.0,2.0])

In [ ]:
b=np.array([3.0,4.0])

In [ ]:
np.any(a<b)

In [ ]:
a= np.arange(1,5)
a

In [ ]:
b =a[::-1]
b

In [ ]:
##  are all elementts satisfying the condition or not?

In [ ]:
arr=np.array([-3,4,27,34,-2,0-45,11,4,0])

In [ ]:
arr

In [ ]:
np.where(arr>0,1,-1)

In [ ]:
m= np.arange(1,13)

In [ ]:
m.ndim

In [ ]:
m.reshape(1,12)

In [ ]:
m.reshape(1,12).ndim

In [ ]:
m.reshape(3,4)

In [ ]:
m2=m.reshape(2,6)

In [ ]:
m.T

In [ ]:
m.reshape(2,6).T

In [ ]:
m.reshape(2,6).flatten

In [ ]:
m2

In [ ]:
m2.T

In [ ]:
m2.flatten()

In [ ]:
m2

In [ ]:
m2.ravel()

In [ ]:
m2

In [ ]:
m1= np.arange(1,10).reshape(3,3)
m1

In [ ]:
m1.ndim

In [ ]:
m1[1]

In [ ]:
m1[1][1]

In [ ]:
m1[0][1]

In [ ]:
row=[0,2,2]
columns=[2,0,2]

In [ ]:
m1[row,columns]

In [ ]:
m1[[0,1],[0,2]]

In [ ]:
##Axis

In [ ]:
# axis= 0

In [ ]:
m1

In [ ]:
np.mean(m1, axis =0)

In [ ]:
np.mean(m1[:, [0,2]], axis=0)

In [ ]:
#Axis =1 (row wise)

In [ ]:
np.max(m1,axis=0)

In [ ]:
np.max(m1,axis=1)

In [ ]:
## numpy 4

In [ ]:
a=[1,2,3,4,5,6]

In [ ]:
a

In [ ]:
a[4:]

In [ ]:
a[::2]

In [ ]:
list_m=[[1,2,3],[1,2,45,54],[78,56,42,1,2,3,4,1]]
list_m

In [ ]:
list_m[:2]

In [ ]:
list_m[2][::2]

In [ ]:
m1=np.arange(1,13)
m1

In [ ]:
m1.size

In [ ]:
m1.ndim

In [ ]:
m1.reshape(3,4)

In [ ]:
m1[:2]

In [ ]:
m1

In [ ]:
m2=m1.reshape(3,4)

In [ ]:
m2

In [ ]:
m2[:2,:2]

In [ ]:
m2.ndim

In [ ]:
### fetch fisrt 2 columns

In [ ]:
m2[:,:2]

In [ ]:
## specific column

In [ ]:
m2[:,[0,2]]

In [ ]:
m3= np.arange(1,31).reshape(3,10)
m3

In [ ]:
m2.shape

In [ ]:
m3[:,[1,3,5,7,9]]

In [ ]:
m3[:,1:5]

In [ ]:
m3[:,1:5:1]

In [ ]:
m3[:,1::2]

In [ ]:
## Fancy Indexing(masking)

In [ ]:
a=np.array([1,2,3,4,5,6])

In [ ]:
a

In [ ]:
a%3==0

In [ ]:
a[a%3==0]

In [ ]:
mask_divisible_by_3=(a%3==0)

In [ ]:
a[mask_divisible_by_3]

In [ ]:
## extend masking to 2d arrays

In [ ]:
m1=np.arange(0,12).reshape(3,4)
m1

In [ ]:
condition=m1<6 ## condition==mask

In [ ]:
condition.shape

In [ ]:
condition

In [ ]:
m1

In [ ]:
m1>3

In [ ]:
m1[m1>3]

In [ ]:
m1[m1>3].reshape(4,2)

In [ ]:
##fetch index where mask is true

In [ ]:
m1

In [ ]:
m1%2==0

In [ ]:
np.argwhere(m1%2==0)

In [ ]:
m2=np.arange(0,23,2)
m2

In [ ]:
m2%5==0

In [ ]:
m2[m2%5==0]

In [ ]:
np.argwhere(m2%5==0)

In [ ]:
~(m2%5==0)

In [ ]:
m2[~(m2%5==0)]

In [ ]:
np.argwhere((~(m2%5==0)))

In [ ]:
any_array=np.arange(1,50,3)
any_array

In [ ]:
any_array[2:5]

In [ ]:
np.sum(any_array)

In [ ]:
np.sum(any_array[2:5])

In [ ]:
income = np.array([100,50,76,89,56,52])
income

In [ ]:
expenses = np.array([67,54,12,90,42,37])
expenses

In [ ]:
condition = income > 50

In [ ]:
income[condition]

In [ ]:
expenses[condition] ### expense of people having income greater than 50

In [ ]:
data = np.loadtxt('fit.txt ' , dtype = str)

In [ ]:
data

In [ ]:
data.shape

In [ ]:
 date=data[:,0]
date

In [ ]:
step_count=data[:,1]
step_count

In [ ]:
mood=data[:,2]
mood

In [ ]:
calories=data[:,3]
calories

In [ ]:
hours_of_sleep = data[:,4]

In [ ]:
hours_of_sleep

In [ ]:
activity_status=data[:,5]
activity_status

In [ ]:
type(calories[0])

In [ ]:
### every column has datatype as string we need to convert it according ot out need


In [ ]:
calories= np.array(calories, dtype='int')

In [ ]:
calories

In [ ]:
hours_of_sleep=np.array(hours_of_sleep, dtype='int')
hours_of_sleep

In [ ]:
step_count=np.array(step_count, dtype='int')

In [ ]:
step_count

In [ ]:
### is there a relationship between step count ,calories and mood?

In [ ]:
step_count

In [ ]:
step_count.mean()

In [ ]:
calories.mean()

In [ ]:
mask=step_count>step_count.mean()

In [ ]:
mask

In [ ]:
calories[mask]

In [ ]:
condition=calories[mask]>np.mean(calories)
condition

In [ ]:
condition.isTrue()

In [ ]:
np.all(~(calories[mask]<np.mean(calories)))

In [ ]:
np.all(condition)

In [ ]:
mood

In [ ]:
np.unique(mood , return_counts=True)

In [ ]:
### step_count vs mood

In [ ]:
np.mean(step_count[mood=='Sad'])

In [ ]:
np.mean(step_count[mood=='Happy'])

In [ ]:
### what is the ususal mood when step count>4000

In [ ]:
np.unique((mood[step_count > 4000]),return_counts='True')

In [ ]:
### numpy 6

In [ ]:
b=np.arange(24)
b

In [ ]:
b=b.reshape(2,3,4)
b

In [ ]:
b[1,2,2 ]

In [ ]:
a= np.arange(4)

In [ ]:
b=a
b

In [ ]:
b[0]=100

In [ ]:
a

In [ ]:
b=a.reshape(2,2)
b

In [ ]:
b[0]=100
b

In [ ]:
a

In [ ]:
a= np.arange(4)
a

In [ ]:
c=a+2
c

In [ ]:
a[0]=100

In [ ]:
a

In [ ]:
c

In [ ]:
np.shares_memory(a,c)

In [ ]:
## splitting

In [ ]:
a=np.random.rand(9)

In [ ]:
a

In [ ]:
np.split(a,3)

In [ ]:
### we can split it unevenly

In [ ]:
np.split(a, [3,5,7])

In [ ]:
b=np.random.randint(0,11)
b

In [ ]:
## hsplit

In [ ]:
x=np.arange(16).reshape(4,4)
x

In [ ]:
np.hsplit(x,2)

In [ ]:
np.vsplit(x,2)

In [ ]:
np.hsplit(x,[0,2,4])

In [ ]:
np.vsplit(x,2)

In [ ]:
np.vsplit(x,[2,4])

In [ ]:
a= np.arange(24).reshape(4,6)
a

In [ ]:
b=np.arange(24,48).reshape(4,6)
b

In [ ]:
np.vstack([a,b])

In [ ]:
np.hstack([a,b])

In [ ]:
## CONCATENATE

In [ ]:
np.concatenate([a,b])

In [ ]:
np.concatenate([a,b], axis= 0)

In [ ]:
np.concatenate([a,b], axis= 1)

In [ ]:
a.reshape(4,-1,3)

In [ ]:
np.expand_dims(a, axis=1)

In [ ]:
a

In [ ]:
b= np.arange(24)

In [ ]:
np.expand_dims(b, axis=0)

In [ ]:
b[:,np.newaxis]

In [ ]:
x=b.reshape(2,3,4)

In [ ]:
x.flatten()

In [ ]:
x

In [ ]:
np.squeeze(a,axis=0)